### PR TITLE
Make the Packages dir clear

### PR DESCRIPTION
**Pull request by hyouuu**
As many (including me) thought it's the ST3.app/contents/Packages

### CODE REVIEW

**Comment by lunixbochs** [comment]
This only applies to mac, and actualvim should work on Linux as well.

Maybe referencing `(Preferences -> Browse Packages...)` and `sublime.packages_path()` would be better.

**Comment by hyouuu** [comment]
Thanks for the idea and implementation! I used it but it doesn't integrate well with the UI parts of ST3 - e.g. search highlighting, cursor appearance, and more importantly, my vimrc's Vim-Plug installations wouldn't work - anyway to make it work?

Thanks again!

**Comment by lunixbochs** [comment]
Neovim should fix all of this: https://github.com/lunixbochs/actualvim/tree/neovim

Stay tuned.

**Comment by lunixbochs** [comment]
What's the cursor appearance complaint?

**Comment by hyouuu** [comment]
Firstly, some issues with neovim branch startup:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/shawngong/Library/Application Support/Sublime Text 3/Packages/actualvim/actual.py", line 6, in <module>
    from .neo import Vim
ImportError: No module named 'actualvim.neo'
reloading plugin actualvim.commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/shawngong/Library/Application Support/Sublime Text 3/Packages/actualvim/commands.py", line 1, in <module>
    from .actual import ActualVim
  File "/Users/shawngong/Library/Application Support/Sublime Text 3/Packages/actualvim/actual.py", line 6, in <module>
    from .neo import Vim
ImportError: No module named 'actualvim.neo'

**Comment by hyouuu** [comment]
Then demonstration about the cursor difference in Vintageous
Normal mode:
screen shot 2017-02-19 at 4 57 28 pm

Insert mode:
screen shot 2017-02-19 at 4 57 33 pm

But with actualvim (last time when it was able to use), it seems there's no indication of Normal vs Insert mode

Finally for native search it would highlight like this:
screen shot 2017-02-19 at 4 57 53 pm

Which is not present with actualVim I think (vintageous also only highlights before you tap enter)

**Comment by hyouuu** [comment]
btw updated the PR to reflect your comment ;)

**Comment by lunixbochs** [comment]
Force pushed a fix for `from .neo import Vim`.

Don't edit any files you care about with the neovim branch yet. It will destroy them.

**Comment by hyouuu** [comment]
Haha let me know when it's in working state - thanks again for this!

**Comment by lunixbochs** [comment]
try it now

**Comment by lunixbochs** [comment]
And thanks! I redid the readme in the neovim branch. You can subscribe to #38 if you want to know how neovim support is going (it's almost ready, just need to fix the hanging bug!)

**Pull request closed without merging**
