### PR TITLE
fixed problem of move right when has unicode character

### PR DESCRIPTION
**Pull request by ghking1**
fixed the unicode problem which will cause decode error when half of unicode character display on top-left in back-end vim

### CODE REVIEW

**Comment by lunixbochs** [comment]
I don't like this solution, I think there must be a better way

**Comment by lunixbochs** [comment]
Tempted to use something like this (this might be off-by-one, haven't tested). As a bonus it saves on double encoding and doesn't even encode the whole line.

```
import itertools

byte_columns = itertools.accumulate(len(c.encode('utf8')) for c in line)
for vcol, bcol in enumerate(byte_columns):
    if bcol >= col:
        break

return view.text_point(row, vcol)
```

**Comment by ghking1** [comment]
I think it's ok, but you should add some comment. Because no one will know why you do it.

**Comment by ghking1** [comment]
I'm not good at python. Can you solve the problem that cursor will move out of screen when col is very large. you should test with unicode character.

**Comment by ghking1** [comment]
@lunixbochs hello, I have added some code to avoid crash unexpectly, if you think it has problem, please refine it.

**Comment by lunixbochs** [comment]
Please open a new pull request and write a message describing the error you saw and what you did to trigger it. Don’t bundle entirely new functionality into a pull request about something else.

**Pull request closed without merging**
